Repository percona/everest, pull requests merged in 2025-06, with the labels that each got.

#1383 EVEREST-1964 | Change label in basic details
  ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/basic-information/basic.tsx
  ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.messages.ts
  ui/apps/everest/src/pages/db-cluster-details/cluster-overview/overview-section/overview-section.messages.ts
  ui/apps/everest/src/pages/db-cluster-details/cluster-overview/overview-section/overview-section.tsx
  ui/apps/everest/src/pages/db-cluster-details/cluster-overview/overview-section/overview-section.types.ts
Labels: auto-update-base, feature-build

#1288 EVEREST-1946 | change upscaling warning message
  ui/apps/everest/src/components/cluster-form/resources/messages.tsx
  ui/apps/everest/src/components/cluster-form/resources/resources.tsx
Labels: auto-update-base, feature-build

#1320 EVEREST-2001 | resource edit field ui fix
  ui/apps/everest/src/components/cluster-form/resources/resources.tsx
Labels: auto-update-base, feature-build

#1273 EVEREST-1958 | fix resources accordion toggle during editing when there are errors
  ui/apps/everest/src/components/cluster-form/resources/resources.tsx
Labels: auto-update-base, feature-build

#1371 Everest-2005 add view details in actions menu
  ui/apps/everest/src/components/db-actions/db-actions.messages.tsx
  ui/apps/everest/src/components/db-actions/db-actions.tsx
  ui/apps/everest/src/components/db-actions/db-actions.types.ts
  ui/apps/everest/src/pages/databases/DbClusterView.tsx
  ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.tsx
Labels: auto-update-base, feature-build

#1415 EVEREST-1909 Prevent duplicate IP [FB]
  internal/server/handlers/validation/database_cluster.go
  internal/server/handlers/validation/database_cluster_test.go
  internal/server/handlers/validation/errors.go
  ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration-schema.ts
  ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
  ui/apps/everest/src/components/cluster-form/advanced-configuration/messages.ts
  ui/apps/everest/src/consts.ts
  ui/apps/everest/src/pages/database-form/database-form-body/steps/advanced-configurations/advanced-configurations.test.tsx
  ui/apps/everest/src/pages/database-form/database-form-body/steps/monitoring/monitoring.test.tsx
Labels: feature-build

#1147 Everest-1895 | fix changing pitr date
  ui/apps/everest/.e2e/pr/db-restore/db-cluster-restore-action.e2e.ts
  ui/apps/everest/src/hooks/api/backups/useBackups.ts
  ui/apps/everest/src/modals/restore-db-modal/restore-db-modal-schema.ts
  ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
  ui/apps/everest/src/pages/databases/DbClusterView.utils.ts
  ui/apps/everest/src/pages/databases/lastBackup/LastBackup.tsx
  ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
  ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/backups-details.tsx
  ui/apps/everest/src/shared-types/backups.types.ts
  ui/packages/ui-lib/src/form/inputs/date-time-picker/date-time-picker.tsx
Labels: auto-update-base, feature-build

#1330 EVEREST-1993 - Add tests for storage scaling
  ui/apps/everest/.e2e/release/storage-scaling.e2e.ts
  ui/apps/everest/src/components/cluster-form/resources/constants.ts
  ui/apps/everest/src/components/cluster-form/resources/messages.tsx
  ui/apps/everest/src/components/cluster-form/resources/resources.tsx
  ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources/resources-edit-modal.test.tsx
Labels: auto-update-base, feature-build

#1252 EVEREST-1838 | disable PITR after no schedules or backups are left
  ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.messages.tsx
  ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
  ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/table-header/backups-list-table-header.messages.tsx
  ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/table-header/backups-list-table-header.tsx
  ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/table-header/backups-list-table-header.types.ts
  ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/table-header/scheduled-backups-list.tsx
  ui/apps/everest/src/utils/db.tsx
Labels: auto-update-base, feature-build

#1418 EVEREST-2030: set NULL API interceptors after logout
  ui/apps/everest/src/api/api.ts
Labels: auto-update-base
