Repository percona/everest, pull requests merged in 2025-07, with the labels that each got.

#1468 Add UI deps scaning to dependabot
  .github/dependabot.yml
  go.mod
  go.sum
Labels: auto-update-base

#1527 Fix tilt after migrating to `go tool`
  .github/workflows/cli-tests.yml
  Makefile
  api/everest-server.gen.go
  client/everest-client.gen.go
  dev/Tiltfile
  go.mod
  go.sum
Labels: auto-update-base

#1528 Enable cache for Go builds and dependency modules
  .github/workflows/cli-tests.yml
  .github/workflows/dev-be-ci.yaml
  .github/workflows/dev-build.yaml
  .github/workflows/dev-fe-e2e.yaml
  .github/workflows/release.yml
Labels: auto-update-base

#1526 EVEREST-2165 | Add show-hide functionality for password
  ui/apps/everest/src/pages/settings/monitoring-endpoints/createEditModal/create-edit-modal.tsx
Labels: auto-update-base, feature-build

#1381 EVEREST-1999 | Helm chart improvements
  .github/workflows/feature-build.yaml
  dev/fb/upgrade-helm.sh
  go.mod
  go.sum
  pkg/cli/helm/installer.go
  pkg/cli/helm/utils/utils.go
  pkg/cli/helm/values.go
  pkg/cli/upgrade/steps.go
  pkg/cli/utils/utils.go
Labels: auto-update-base, feature-build

#1460 EVEREST-2017 Fix MinIO restore from on-demand backup
  go.mod
  go.sum
  ui/apps/everest/.e2e/release/restore-new-cluster.e2e.ts
Labels: feature-build

#1424 EVEREST-2097 | diagram view text outside the box fix
  ui/apps/everest/src/pages/db-cluster-details/components/diagram-view/constants.ts
  ui/apps/everest/src/pages/db-cluster-details/components/diagram-view/container-node.tsx
  ui/apps/everest/src/pages/db-cluster-details/components/diagram-view/diagram-node.tsx
Labels: auto-update-base, feature-build

#1466 EVEREST-2031 / fix policy dialog input size
  ui/apps/everest/src/pages/settings/pod-scheduling-policies/policies-dialog.tsx
  ui/packages/ui-lib/src/form/inputs/text/text.tsx
  ui/packages/ui-lib/src/form/inputs/text/text.types.ts
Labels: auto-update-base, feature-build

#1436 [UI] EVEREST-2105 Fix cluster name generation for WizardMode.Restore
  ui/apps/everest/src/pages/database-form/database-form.utils.ts
Labels: feature-build

#1530 EVEREST-2101 | Add new button limit and e2e tests
  ui/apps/everest/.e2e/pr/db-cluster/db-wizard/create-db-cluster/errors-handling.e2e.ts
  ui/packages/ui-lib/src/form/inputs/text-array/text-array.tsx
Labels: auto-update-base, feature-build
